version: '{build}'

image: Visual Studio 2017
shallow_clone: true

matrix:
    fast_finish: true

platform:
    -x64

install:
    set PATH=%PATH%;C:\cygwin\bin

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - make.exe msvc -j4 CXXFLAGS="/std:c++17 /W3 /I tests /I include"

artifacts:
    - path: expected_test.exe

test_script:
    - call ci/verify.bat
