version: 1.0.'{build}'

image: Visual Studio 2017
shallow_clone: true

matrix:
    fast_finish: true

platform:
    -x64

install:
    set PATH=%PATH%;c:\cygwin\bin

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - set CXX=cl.exe
    - make.exe msvc -j4
