image: archlinux/base:latest

before_script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S gcc clang make

stages:
    - build
    - test

gcc:
    stage: build
    script:
    - export CXX=g++
    - make
    artifacts:
        paths:
        - expected_test

clang:
    stage: build
    script:
    - export CXX=clang++
    - make
    - ci/verify

unit_tests:
    stage: test
    script:
    - ci/verify
