image: archlinux/base:latest

before_script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S grep gcc clang make

stages:
    - build
    - test

gcc:
    stage: build
    script:
    - export CXX=g++
    - make -j$(nproc) BIN=gcc_expected_test
    artifacts:
        paths:
        - gcc_expected_test

clang:
    stage: build
    script:
    - export CXX=clang++
    - make -j$(nproc) BIN=clang_expected_test

gcc_tests:
    stage: test
    script:
    - ci/verify gcc_expected_test

clang_tests:
    stage: test
    script:
    - ci/verify clang_expected_test
