#!/bin/bash

output="$(./expected_test)"
retval=$?

exit_code=0

if ! echo "$output" | grep -q 'All tests passed'; then
    printf "Tests failed:\n%s\n\n" "$output"
    exit_code=1
else
    printf "%s\n\n" "$output"
fi

printf "Process returned %s\n" "$retval"
if (( $retval != 0 )) ; then
    exit_code=1
fi

exit $exit_code
