#!/bin/bash

bin="expected_test"
output=./$bin
retval=$?

echo "Process returned "$retval
if (( $retval != 0 )) ; then
    exit 1
fi

if ! $output | grep -q "All tests passed" ; then
    echo "Tests failed"
    exit 1
else
    echo "All tests passed"
fi
